version: "3"

services:
  mariadb:
    image: mariadb:10.3
    ports:
      - "3306:3306"
    volumes:
      - ${PWD}/data/mariadb:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "shrtdb"
      MYSQL_USER: "admin"
      MYSQL_PASSWORD: "supersecret"
  monolith:
    build:
      context: monolith
    ports:
      - "8080:8080"
    depends_on:
      - mariadb
      - kafka
    environment:
      SPRING_DATASOURCE_URL: "jdbc:mariadb://mariadb:3306/shrtdb"
      KAFKA_BROKERS: "kafka:9092"
    command: java -Djava.security.egd=file:/dev/./urandom -jar /app/target/shrtr-0.0.1-SNAPSHOT.jar
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 1m30s
      timeout: 10s
      retries: 3

  kafka:
    image: vectorized/redpanda
    command:
      - redpanda
      - start
      - --smp
      - '1'
      - --reserve-memory
      - 0M
      - --overprovisioned
      - --node-id
      - '0'
      - --kafka-addr
      - PLAINTEXT://0.0.0.0:29092,OUTSIDE://0.0.0.0:9092
      - --advertise-kafka-addr
      - PLAINTEXT://kafka:29092,OUTSIDE://kafka:9092
    ports:
      - "29092:29092"
      - "9092:9092"

  reporting__service:
    depends_on:
      - reporting__es01
      - kafka
    build:
      context: reporting-service
    environment:
      ES_HOSTS: "http://reporting__es01:9200"
      KAFKA_BROKERS: "kafka:9092"

  reporting__api:
    depends_on:
      - reporting__es01
    build:
      context: reporting-api
    environment:
      ES_HOSTS: "http://reporting__es01:9200"
    ports:
      - 8081:3000
  reporting__es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.0.1
    ports:
      - 9200:9200
    environment:
      - node.name=es01
      - cluster.name=reporting
      - cluster.initial_master_nodes=es01
      - discovery.seed_hosts=
      - ELASTIC_PASSWORD=1234
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - xpack.security.transport.ssl.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -s --cacert config/certs/ca/ca.crt https://localhost:9200 | grep -q 'missing authentication credentials'",
        ]
      interval: 10s
      timeout: 10s
      retries: 120

