version: "3"

services:

  gateway:
    build:
      context: gateway
    ports:
      - 8079:3000
    environment:
      AUTH_HOST: "http://auth-api:8080"

  mariadb:
    image: mariadb:10.3
    volumes:
      - ${PWD}/data/mariadb:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "shrtdb"
      MYSQL_USER: "admin"
      MYSQL_PASSWORD: "supersecret"
  monolith:
    build:
      context: monolith
    depends_on:
      - mariadb
      - kafka
    environment:
      SPRING_DATASOURCE_URL: "jdbc:mariadb://mariadb:3306/shrtdb"
      KAFKA_BROKERS: "kafka:9092"
    command: java -Djava.security.egd=file:/dev/./urandom -jar /app/target/shrtr-0.0.1-SNAPSHOT.jar
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 1m30s
      timeout: 10s
      retries: 3
  auth-api:
    build:
      context: auth-api
    depends_on:
      - mariadb
      - kafka
    environment:
      SPRING_DATASOURCE_URL: "jdbc:mariadb://mariadb:3306/shrtdb"
      KAFKA_BROKERS: "kafka:9092"
    command: java -Djava.security.egd=file:/dev/./urandom -jar /app/target/shrtr-0.0.1-SNAPSHOT.jar
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/actuator/health" ]
      interval: 1m30s
      timeout: 10s
      retries: 3

  kafka:
    image: vectorized/redpanda
    command:
      - redpanda
      - start
      - --smp
      - '1'
      - --reserve-memory
      - 0M
      - --overprovisioned
      - --node-id
      - '0'
      - --kafka-addr
      - PLAINTEXT://0.0.0.0:29092,OUTSIDE://0.0.0.0:9092
      - --advertise-kafka-addr
      - PLAINTEXT://kafka:29092,OUTSIDE://kafka:9092

  reporting__service:
    depends_on:
      - reporting-es01
      - kafka
    build:
      context: reporting-service
    environment:
      ES_HOSTS: "http://reporting-es01:9200"
      KAFKA_BROKERS: "kafka:9092"

  reporting__api:
    depends_on:
      - reporting-es01
    build:
      context: reporting-api
    environment:
      ES_HOSTS: "http://reporting-es01:9200"

  reporting-es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.0.1
    environment:
      - node.name=es01
      - cluster.name=reporting
      - cluster.initial_master_nodes=es01
      - discovery.seed_hosts=
      - ELASTIC_PASSWORD=1234
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - xpack.security.transport.ssl.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1

